# Evaluating Model Performance

In [1]:
#option 1
#use all available data for training and test on the same dataset

In [2]:
#option2
#split available dataset into training and test sets

In [3]:
#option 
#K fold cross validation

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [5]:
digits = load_digits()

In [9]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [15]:
LR = LogisticRegression()
LR.fit(X_train, y_train)
LR.score(X_test, y_test)

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [16]:
SVM = SVC()
SVM.fit(X_train, y_train)
SVM.score(X_test, y_test)


0.9851851851851852

In [20]:
RF = RandomForestClassifier(n_estimators=40)
RF.fit(X_train, y_train)
RF.score(X_test, y_test)

0.9592592592592593

In [24]:
from sklearn.model_selection import KFold

In [26]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [28]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [32]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [33]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9851851851851852

In [35]:
from sklearn.model_selection import StratifiedKFold

In [36]:
folds = StratifiedKFold(n_splits=3)

In [48]:
#code_1
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
    digits.target[train_index], digits.target[test_index]
    
    print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9232053422370617
0.9666110183639399
0.9365609348914858
0.9415692821368948


/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9816360601001669
0.9582637729549248
0.9148580968280468


/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9549248747913188
0.9298831385642737


In [47]:
#print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))

In [45]:
#print(get_score(SVC(), X_train, X_test, y_train, y_test))

In [46]:
#print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [50]:
scores_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [51]:
scores_lr

[0.9148580968280468, 0.9148580968280468]

In [54]:
scores_svm

[0.9549248747913188, 0.9549248747913188]

In [55]:
scores_rf

[0.9248747913188647]

In [56]:
from sklearn.model_selection import cross_val_score

In [57]:
cross_val_score(LogisticRegression(), digits.data, digits.target)
#it simplies the code_1 above

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [59]:
cross_val_score(SVC(), digits.data, digits.target)#it simplies the code_1 above

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [60]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)
#it simplies the code_1 above

array([0.925     , 0.88055556, 0.95264624, 0.96657382, 0.9275766 ])