In [2]:
#home prices in monroe township new jersy usa

In [3]:
#price = m1*area + m2*bedrooms + m3*age + b---->m1,m2,m3 are coefficients
#area, bedrooms and age are independent variables (features)

In [5]:
import pandas as pd
import numpy as numpy
from sklearn import linear_model

In [6]:
df = pd.read_csv("house_prices_multivariate.csv")

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
import math
df.bedrooms.median()#calculates the median

3.5

In [9]:
median_bedrooms = math.floor(df.bedrooms.median())#lets stick to whole numbers

In [10]:
median_bedrooms

3

In [11]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [14]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [16]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [17]:
reg = linear_model.LinearRegression()

In [18]:
reg

LinearRegression()

In [19]:
reg.fit(df[["area", "bedrooms", "age"]], df.price)

LinearRegression()

In [20]:
reg.coef_#checks coefficients

array([   137.25, -26025.  ,  -6825.  ])

In [22]:
reg.intercept_

383725.00000000006

In [23]:
reg.predict([[3000, 3, 40]])

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [24]:
#how the algorithm got 444400

In [26]:
137.25*3000+(-26025*3)+(-6825*40)+383725#

444400.0

In [27]:
reg.predict([[2500,4,5]])

/home/wanyoike/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])